### ISSUE TITLE
Camera File naming convention messed up in French?

### ISSUE THREAD

**Issue by Andydi** [ingbrzy/MIUI-Global-xml-V8-FRENCH#13]
Posted this bug on Xiaomi.eu forum
"Is it possible to modify the Camera File naming convention?
        Now it's IMG_MMDD**YYYY**_HHMMSS.jpg ----> a complete mess
        it should be IMG_**YYYY**MMDD_HHMMSS.jpg ---> automatic chronological sorting
        Because it has to do with dates, this might be a localization issue specific to Europe.
        Is there a parameter file that can be tweaked or even better a modification in future roms possible?
        Thanks in advance!"
ingbrzy replied:
    "Which language? It's translation issue.. Report it to your lang repo.."

Is it possible to check if something went wrong in the French localization?
Thank you!

**Comment by manzing** [comment]
Hi
What is the version of your rom ?
I've just shot a picture in Xiaomi.eu 6,11,17 (french) and the name format is : IMG_20161120_163908
So filename is exactly what you want isn't it ?

**Comment by ingbrzy** [comment]
@Andydi which rom are you using? Post screenshot from about phone screen..

**Comment by Andydi** [comment]
I'm using stable 8.0.3.0 I will cinsider switching to weekly...

**Comment by manzing** [comment]
@ingbrzy Does the 8.0.3.0 use the same repository for translation ?
If so i can't understand what happens.

**Comment by ingbrzy** [comment]
nope.. it used old translation.. so update your ROM and it should be solved...
