### ISSUE TITLE
update global 7.3.2

### ISSUE THREAD

**Issue by discom38** [ingbrzy/MIUI-Global-xml-V8-FRENCH#21]
@ingbrzy 
I'm a bit upset of how the translation is managed.

We did a lot of fixes in the global translation since the previous import (translations who are not even present on your import), and now i see that you just overwrite the repository with a new import of the global dev version. (commit : update global 7.3.2)

Yes, the repo didn't move for 2 months, but i was not a so long time.

You thrown in the trash all of our work without any word neither on the forum, neither here.
I am disappointed.

**Comment by ingbrzy** [comment]
Well, how do you want to keep translation updated + your fixes..? as you dont push new xmls, just fix typos...

**Comment by BenoitPoulet** [comment]
I think he complain about the lack of discussion with peoples who contribute to the project.

You acted without saying anything, without warning.
